# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XgPJV0TVYfEEhgALcfdZv2Om0XNZKWvC

1. Import libraries and load dataset
"""

import pandas as pd
import plotly.express as px

# Load dataset
df = pd.read_csv("global air pollution dataset.csv")

# Display first five rows
print(df.head())

# Display column names
print(df.columns)

"""2. Interactive Bar Chart
Average AQI by Country
"""

country_aqi = (
    df.groupby("Country")["AQI Value"]
    .mean()
    .reset_index()
    .sort_values("AQI Value", ascending=False)
)

fig = px.bar(
    country_aqi.head(15),
    x="Country",
    y="AQI Value",
    title="Top 15 Countries by Average AQI",
    labels={
        "AQI Value": "Average AQI",
        "Country": "Country"
    }
)

fig.show()

"""Bar Chart — AQI by City"""

city_aqi = (
    df.groupby("City")["AQI Value"]
    .mean()
    .reset_index()
    .sort_values("AQI Value", ascending=False)
)

fig = px.bar(
    city_aqi.head(20),
    x="City",
    y="AQI Value",
    title="Top 20 Cities by Average AQI",
    labels={
        "AQI Value": "Average AQI",
        "City": "City"
    }
)

fig.show()

fig = px.bar(
    country_aqi.head(15),
    x="AQI Value",
    y="Country",
    orientation="h",
    title="Average AQI by Country",
    labels={
        "AQI Value": "Average AQI",
        "Country": "Country"
    }
)

fig.show()

"""Interactive Pie Chart
AQI Category Distribution
"""

aqi_category = df["AQI Category"].value_counts().reset_index()

aqi_category.columns = ["AQI Category", "Count"]
print(aqi_category.head())
fig = px.pie(
    aqi_category,
    names="AQI Category",
    values="Count",
    title="Distribution of AQI Categories",
    hole=0.3
)

fig.show()

# 3. HISTOGRAM
# ==================================================

fig = px.histogram(
    df,
    x="AQI Value",
    title="AQI Distribution",
    nbins=30
)

fig.show()

# 4. BOX PLOT
# ==================================================

fig = px.box(
    df,
    x="AQI Category",
    y="AQI Value",
    title="AQI Distribution by Category"
)

fig.show()

#5. SCATTER PLOT
# ==================================================

fig = px.scatter(
    df,
    x="PM2.5 AQI Value",
    y="AQI Value",
    color="AQI Category",
    hover_name="City",
    hover_data=["Country"],
    title="PM2.5 AQI vs Overall AQI"
)

fig.show()

# 6. POLLUTANT COMPARISON
# ==================================================

pollutants = pd.DataFrame({

    "Pollutant": [
        "CO",
        "Ozone",
        "NO2",
        "PM2.5"
    ],

    "Average AQI": [
        df["CO AQI Value"].mean(),
        df["Ozone AQI Value"].mean(),
        df["NO2 AQI Value"].mean(),
        df["PM2.5 AQI Value"].mean()
    ]
})


fig = px.bar(
    pollutants,
    x="Pollutant",
    y="Average AQI",
    title="Average AQI by Pollutant",
    text_auto=".2f"
)

fig.show()

# 7. HEATMAP
# ==================================================

corr = df[
    [
        "AQI Value",
        "CO AQI Value",
        "Ozone AQI Value",
        "NO2 AQI Value",
        "PM2.5 AQI Value"
    ]
].corr()


fig = px.imshow(
    corr,
    text_auto=True,
    title="AQI and Pollutant Correlation"
)

fig.show()

# 8. 3D SCATTER
# ==================================================

fig = px.scatter_3d(
    df,
    x="CO AQI Value",
    y="NO2 AQI Value",
    z="PM2.5 AQI Value",
    color="AQI Category",
    hover_name="City",
    title="3D Air Pollution Visualization"
)

fig.show()

"""Plotly geographical heat map"""

# Load dataset
df = pd.read_csv("air_pollution_location_heatmap.csv")

# Create geographical map
fig = px.scatter_geo(
    df,
    lat="Latitude",
    lon="Longitude",
    color="AQI",
    size="AQI",
    hover_name="City",
    hover_data={
        "Country": True,
        "AQI": True,
        "Latitude": False,
        "Longitude": False
    },
    projection="natural earth",
    color_continuous_scale="RdYlGn_r",
    title="Air Pollution Across Indian Cities"
)

fig.show()

fig.update_geos(
    center=dict(lat=22.5, lon=79),
    projection_scale=4
)

fig.show()